SunriseWeb/Controllers/ViewHDImageController.cs
using Lib.Models;
using SunriseWeb.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;


namespace SunriseWeb.Controllers
{
    public class ViewHDImageController : Controller
    {
        API _api = new API();
        // GET: ViewHDImage
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetHDVideodDetail (string sRefNo)
        {
            var input = new
            {
                RefNo = sRefNo
            };
            string inputJson = (new JavaScriptSerializer()).Serialize(input);
            string _response = _api.CallAPIWithoutToken(Constants.GetViewHDImage, inputJson);
            ServiceResponse<ViewHDImageResponse> _data = (new JavaScriptSerializer()).Deserialize<ServiceResponse<ViewHDImageResponse>>(_response);
            return Json(_data, JsonRequestBehavior.AllowGet);
        }
    }
}

SunriseWeb/Views/ViewHDImage/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<meta name="format-detection" content="telephone=no" />
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <link rel="shortcut icon" href="~/Content/images/nav-logo.png" type="image/x-icon" />
    <title>Sunrise Dimaonds</title>
    <link rel="stylesheet" href="~/Content/css/bootstrap.min.css" />
    <link href="~/Content/css/flaticon.css" rel="stylesheet" />
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/Plugins/toastr/toastr.css" rel="stylesheet" />
    <link rel="Stylesheet" href="~/Content/OldProject/Style1.css" type="text/css" />

    <style type="text/css">
        .video-container {
            position: relative;
            padding-bottom: 56.25%;
            padding-top: 30px;
            height: 0;
        }

            .video-container iframe, .video-container object, .video-container embed {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
            }
    </style>


</head>
<body>
    @*<div id="header-bg" style="zoom: reset;">
        <div id="header" style="zoom: reset;">

        </div>
    </div>*@
    <center>
        <div class="video-container">
            <div id="divframe" runat="server" frameborder="0" allowfullscreen>
            </div>
        </div>
    </center>

    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/Plugins/jqueryUI/jquery-ui.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/Plugins/toastr/toastr.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Content/OldProject/Magnifier/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            GetDetails();
        });
        function GetDetails() {
            if (getParameterByName("stoneid") != "") {
                  $.ajax({
                    url: "@Url.Action("GetHDVideodDetail", "ViewHDImage")",
                    type: "POST",
                      data: { sRefNo: getParameterByName("stoneid")},
                      success: function (data, textStatus, jqXHR) {
                          if (data.Data != null && data.Data.length > 0) {
                              var L = data.Data.length - 1;
                              _data = data.Data;
                              _len = L;
                              $('#divframe').html(data.Data[L].VideoPath);

                          }
                          else {
                              $('#divframe').html("HD Video Not Available");
                          }
                      },
                      error: function (jqXHR, textStatus, errorThrown) {

                      }
                  });
            }
            else {
                $('#divframe').html("HD Video Not Available");
            }
        }

        function getParameterByName(name) {
            var url = window.location.href;
            name = name.replace(/[\[\]]/g, '\\$&');
            var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
                results = regex.exec(url);
            if (!results) return null;
            if (!results[2]) return '';
            return decodeURIComponent(results[2].replace(/\+/g, ' '));
        }
    </script>
</body>
</html>